branches:
  only:
  - master

language: python

python:
  - 3.4

install:
  - pip install -r requirements.txt --use-mirrors

script:
  - make html

notifications:
  email: false

env:
  global:
    secure: W+ury4ghWd0WjjWiqii6QRyZBxPg0tO+mod7UYxaiT9vAAo6g0zAam6S3li6+NO+/25nCLg1+w0pq6Mw5ZdRvsD6aFEnFQWUoRBdSwvj3QKInCZF2hy8P8IiKFHx+SSdjgn80y5D5An78deORSTdn++v71FFQf4Ob8cERikeATi8hC44fYd3sp3vXGe9mUozoByaguPq/Zd4FUFeRVDVHbY0D3mIA5GSKvnrLLxnsTbzAALncdLMP4SvDDkqvlcuj+uEyijcxwRBpFzx3WW/yQ2KR9GfWOYNp1woQNivP8YUIUkFzWbcCaxyTCL7RLyQCSm3FSuvlQ6Kms3IDAMBCDuajlG//K+Ms3zyOX/Gn0Y+m0UThqH22wZ5AVpVFQeNFkI2URt477hh7iXy9GjkJYgbi9YFzeuhwi7j/Rjk7eSDRyHWuaAzrW/2lmS4y0FcB3nugbLHVZzbAvEe7J+8+IHVdr6jPzOQSulAmOk4CEXhxIZA1lYaWjZMZaGzIqk4qRqsi3Ngq5YwlWe7WowzJ/c5qlpdHJ/sZ3zEMJUQP2RfUvWyxyL6zuz2CRo2yjcunKTaI6DPEBZIHribNwHpQ6toJZKF3dHPPjkm0dAsQe+E8FYCbh3mwWkmOHdZ0E6SFgUf1XiHRuXYThNLk2e9ReElihGeO3Hziz3yfdNTVvw=

after_success: ./deploy.sh
